#!/usr/bin/php
<?php

require 'functions.php';

$idxName = 'faker_data_' . rand(1, 999999);
$type = 'fx_' . rand (0, 9);
$aliasName = 'faker';

# Create Index
$indexParams = [
    'index' =>  $idxName,
];
$client->indices()->create($indexParams);

# Add aliase to Index
$params = [
    'body' => [
        'actions'  => [
            'add' => [
                'index' => $idxName,
                'alias' => $aliasName,
            ]
        ]
    ]
];
$client->indices()->updateAliases($params);


foreach(selectAll() as $data):
    $response = $client->index(
        [
            'index' => $idxName,
            'type'  => $type,
            'body'  => [
                'name' => $data->fullname,
                'address' => $data->address,
                'email' => $data->email,
                'description' => $data->descp,
            ],
        ]
    );
    echo $response['result'] . " sequence no : " . $response['_seq_no'] . "\n";
endforeach;

?>