#!/usr/bin/php
<?php

require 'functions.php';

$idxName1 = 'faker_data_1';
$idxName2 = 'faker_data_2';
$type = 'fx_' . rand (0, 9);
$aliasName = 'faker';

createIndexWithAlias($idxName1, $idxName2, $aliasName);

foreach(selectAll() as $data):
    $response = $client->index(
        [
            'index' => $aliasName,
            'type'  => $type,
            'body'  => [
                'name' => $data->fullname,
                'address' => $data->address,
                'email' => $data->email,
                'description' => $data->descp,
            ],
        ]
    );
    echo $response['result'] . " sequence no : " . $response['_seq_no'] . "\n";
endforeach;

?>